package mobilecrawler;

import java.io.File;
import java.lang.Runtime;
import java.net.URL;
import javax.swing.JFileChooser;
import org.jdesktop.application.Action;

/**
 *
 * @author Jagdish
 */
public class MobileAgentMasterView extends javax.swing.JFrame {

    /** Creates new form MobileAgentMasterView */
    public MobileAgentMasterView() {
        initComponents();
    }
    
    public MobileAgentMasterView(MobileAgentMaster mam)
    {
        initComponents();
        this.mam = mam;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        odbfm_label = new javax.swing.JLabel();
        odbfm_file_text = new javax.swing.JTextField();
        odbfm_file_btn = new javax.swing.JButton();
        startAgent = new javax.swing.JButton();
        destinationLabel = new javax.swing.JLabel();
        destinationText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        odbfm_label.setFont(new java.awt.Font("Tahoma", 0, 18));
        odbfm_label.setText("ODBFM File:");

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(webspider.WebSpiderApp.class).getContext().getActionMap(MobileAgentMasterView.class, this);
        odbfm_file_btn.setAction(actionMap.get("loadODBFM")); // NOI18N
        odbfm_file_btn.setText("...");

        startAgent.setAction(actionMap.get("startAgent")); // NOI18N
        startAgent.setText("Go");

        destinationLabel.setFont(new java.awt.Font("Tahoma", 0, 18));
        destinationLabel.setText("Destination:");

        destinationText.setText("atp://");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(odbfm_label)
                    .addComponent(destinationLabel))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(destinationText, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(odbfm_file_text, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(odbfm_file_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(startAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(odbfm_file_text, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addComponent(odbfm_file_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(odbfm_label, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinationLabel)
                    .addComponent(destinationText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(startAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MobileAgentMasterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MobileAgentMasterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MobileAgentMasterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MobileAgentMasterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MobileAgentMasterView().setVisible(true);
            }
        });
    }

    @Action
    public void loadODBFM() 
    {
        class MyFilter extends javax.swing.filechooser.FileFilter 
        {
            public boolean accept(File file) 
            {
                String filename = file.getName();
                return filename.endsWith(".dat");
            }
            public String getDescription() 
            {
                return "*.dat";
            }
        }
        JFileChooser fc = new JFileChooser();    
        fc.addChoosableFileFilter(new MyFilter());      
        int reval = fc.showOpenDialog(fc);
        if(reval == JFileChooser.APPROVE_OPTION)
        {
            this.odbfm_file_text.setText(fc.getSelectedFile().toString());      
            odbfm_file = new File(this.odbfm_file_text.getText());
            try
            {
                dest = new URL(this.destinationText.getText());
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
    }

    @Action
    public void startAgent() 
    {        
        if((odbfm_file != null) && (dest != null))
        {
            mam.setFile(odbfm_file, dest);
            mam.createChild();
        }
    }
    
    private File odbfm_file;
    private URL dest;
    MobileAgentMaster mam;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel destinationLabel;
    private javax.swing.JTextField destinationText;
    private javax.swing.JButton odbfm_file_btn;
    private javax.swing.JTextField odbfm_file_text;
    private javax.swing.JLabel odbfm_label;
    private javax.swing.JButton startAgent;
    // End of variables declaration//GEN-END:variables
}
